name: My first Workflow

on: 
  workflow_dispatch:
  push:
    branches: 
      - main  

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bom dia NOS 👋"
      - uses: actions/checkout@v4
      - run: ls
      - run: echo "On Push 👋"
